### PR TITLE
Add install.sh

### PR DESCRIPTION
**Pull request by RealMrCactus**
Adds an install.sh and a couple changes in the readme. Please test my curl command before pushing to main as it may not work.

### CODE REVIEW

**Comment by alexpkgs** [comment]
okay imma test it with curl :trollface:

**Comment by alexpkgs** [comment]
image
okay so the main:repo for atto doesn't have the install.sh yet..

**Comment by alexpkgs** [comment]
image
but if i try doing this it works
so i had to change the username
(i don't have cargo installed)

**Comment by RealMrCactus** [comment]
> image
> but if i try doing this it works
> so i had to change the username
> (i don't have cargo installed)

Should be good then, I did forget to do something which was have it automatically delete the repo folder but you can do that if youd like

**Comment by m0th05** [comment]
So we ready to merge?

**Pull request merged**
